jmxtrans/jmxtrans-agent

src/main/java/org/jmxtrans/agent/Query.java
src/main/java/org/jmxtrans/agent/ResultNameStrategy.java
src/main/java/org/jmxtrans/agent/ResultNameStrategyImpl.java
src/test/java/org/jmxtrans/agent/QueryTest.java

As discussed in pull request 29 by @cyrille-leclerc and @petermodzelewski, creating an issue to allow support for null attribute and composite key in the query
References #29
Fixes #34

Allow support for null attribute or key in a query

---

pom.xml
src/main/java/org/jmxtrans/agent/DynamicallyAgentAttacher.java
src/main/java/org/jmxtrans/agent/JmxTransAgent.java

With an "agentmain" method, it is possible to attach the agent to a running JVM.  This PR adds a new class that connects to an existing JVM and attach the agent after the fact.
To use the agent, the absolute paths to both the agent JAR and its configuration must be passed to the launcher, along with the target JVM PID.
Example, assuming the agent is in `/tmp/`, the configuration file is `/tmp/sample-config.xml` and the target JVM has PID `1234`, run the following:
```sh
java \
-cp $JAVA_HOME/lib/tools.jar:/tmp/jmxtrans-agent-1.1.1-SNAPSHOT.jar \
org.jmxtrans.agent.DynamicallyAgentAttacher \
/tmp/jmxtrans-agent-1.1.1-SNAPSHOT.jar \
1234 \
/tmp/sample-config.xml
```

Add support for dynamic agent attachement

---

src/main/java/org/jmxtrans/agent/GraphiteUdpOutputWriter.java
src/test/java/org/jmxtrans/agent/GraphiteUdpOutputWriterTest.java

Implementation of an output writer for Graphite that uses UDP.
There is currently some code duplication with the `GraphitePlainTextTcpOutputWriter`, especially in `buildMetricPathPrefix` and in the configuration key constants. If you accept this PR I can put in some work towards reusing the common parts between the implementations.
Any feedback you have is welcome.

UDP output writer for Graphite

---

src/main/java/org/jmxtrans/agent/JmxTransExporter.java
src/main/java/org/jmxtrans/agent/JmxTransExporterBuilder.java
src/main/java/org/jmxtrans/agent/Query.java
src/test/java/org/jmxtrans/agent/JmxTransExporterBuilderTest.java
src/test/java/org/jmxtrans/agent/QueryTest.java
src/test/resources/jmxtrans-attribute-attributes-exclusive-test.xml
src/test/resources/jmxtrans-multiple-attributes-test.xml
src/test/resources/jmxtrans-no-attributes-specified-generates-wildcard-query-test.xml

We have many cases where we want to collect a subset of the attributes for a MBean. In these cases we want to avoid duplicating the `resultAlias` and `objectName`.
This PR adds support for a comma-separated list of attributes to allow for queries such as:
```
<query objectName="java.lang:type=GarbageCollector,name=*"
attribute="CollectionTime,CollectionCount"
resultAlias="jvm.gc.%name%.#attribute#"/>
```
It looks a bit weird to still have the XML attribute called "attribute" when it in fact supports many attributes. I'm open to suggestions if you want that changed.
If you accept this PR I can update the README with information about this (and about the support for selecting all attributes, which doesn't seem to be clearly documented now).

Support for comma separated list of attributes in a query

---

src/main/java/org/jmxtrans/agent/GraphitePlainTextTcpOutputWriter.java
src/main/java/org/jmxtrans/agent/GraphiteUdpOutputWriter.java
src/main/java/org/jmxtrans/agent/graphite/GraphiteMetricMessageBuilder.java
src/main/java/org/jmxtrans/agent/graphite/GraphiteOutputWriterCommonSettings.java
src/test/java/org/jmxtrans/agent/GraphiteMetricMessageBuilderTest.java
src/test/java/org/jmxtrans/agent/JmxTransExporterBuilderTest.java

I have made some refactoring to the Graphite output writers to reuse the code common to both the TCP and UDP implementation. I felt there was a bit too much duplication after me adding the UDP variant.
* Created `GraphiteMetricMessageBuilder` responsible for generating the actual message, including optionally generating the default prefix.
* Created `GraphiteOutputWriterCommonSettings` to keep setting constants common to both implementation and convenient accessors to the settings.
* Test for `GraphiteMetricMessageBuilder`
Please let me know any feedback you have.
And thank you for the swift handling of my previous work!

Refactoring of Graphite output writers

---

src/main/java/org/jmxtrans/agent/GraphitePlainTextTcpOutputWriter.java

When an exception is thrown while flushing the stream, the socket isn't cleaned up and the agent will continue to use the broken socket.  We are using a hostname for the endpoint.  When we update the endpoint and change IP addresses, the writer will throw an exception for a broken pipe.  The agent will continue to use the socket and get exceptions for a broken pipe until the service is restarted.

Release the connection if the writer fails to flush.

---

src/main/java/org/jmxtrans/agent/ExpressionLanguageEngineImpl.java
src/test/java/org/jmxtrans/agent/ExpressionLanguageEngineTest.java

Some systems (like Solr) may include valuable information in the MXBean
domain. This commit adds two new functions `domain` and
`reversed_domain` which retrieves it, optionally reverse it, and make it
available in the result alias.
Example of Solr MXBean:
```
solr/demo.solr:type=/spell,id=Lazy[solr.SearchHandler]
```
If the domain contains multiple dots, it may be useful to reverse it.
Hence the additional `reversed_domain` function.

Add functions to retrieve the MXBean domain

---

src/main/java/org/jmxtrans/agent/ConfigReloadWatcher.java
src/main/java/org/jmxtrans/agent/ConfigurationChangedListener.java
src/main/java/org/jmxtrans/agent/ConfigurationDocumentLoader.java
src/main/java/org/jmxtrans/agent/GraphitePlainTextTcpOutputWriter.java
src/main/java/org/jmxtrans/agent/JmxTransAgent.java
src/main/java/org/jmxtrans/agent/JmxTransConfigurationDocumentLoader.java
src/main/java/org/jmxtrans/agent/JmxTransExporter.java
src/main/java/org/jmxtrans/agent/JmxTransExporterBuilder.java
src/main/java/org/jmxtrans/agent/JmxTransExporterConfiguration.java
src/test/java/org/jmxtrans/agent/ConfigReloadWatcherTest.java
src/test/java/org/jmxtrans/agent/JmxTransExporterBuilderTest.java
src/test/resources/jmxtrans-config-reload-test.xml

Support for reloading the configuration file at runtime. By adding
```xml
<reloadConfigurationCheckIntervalInSeconds>X</reloadConfigurationCheckIntervalInSeconds>
```
to the configuration, the configuration file is polled every X seconds for changes. The configuration is loaded as an XML document and compared against the current configuration - if changes are detected, the new configuration is loaded. This way we can support URL configuration sources which would not be possible if we only checked file modification timestamps.
This PR became quite big since there were some refactoring required. Currently the `collectInterval` is not updated dynamically - that would have required even more refactoring. I will look into that when I work on issue #56. 
A summary of the changes:
* Added …

Support for dynamic reloading of the configuration file

---

src/main/java/org/jmxtrans/agent/JmxTransExporter.java
src/test/java/org/jmxtrans/agent/util/io/IoUtilsTest.java

Two minor fixes:
* `IoUtilsTest` failed on Windows since file URLs can not contain backslashes and must start with a slash to be absolute.
* The `config` field in `JmxTransExporter` should be volatile since it is written and read by different threads.

Fixed test that was broken on Windows + volatile config

---

src/main/java/org/jmxtrans/agent/DynamicallyAgentAttacher.java
src/main/java/org/jmxtrans/agent/JmxTransAgent.java
src/main/java/org/jmxtrans/agent/graphite/GraphiteOutputWriterCommonSettings.java
src/main/java/org/jmxtrans/agent/util/Preconditions2.java
src/main/java/org/jmxtrans/agent/util/collect/Iterables2.java
src/main/java/org/jmxtrans/agent/util/io/IoUtils.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - “ Utility classes should not have public constructors ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Ayman Abdelghany.

Adding private constructor to util classes (containing static methods only)

---

src/main/java/org/jmxtrans/agent/Collector.java
src/main/java/org/jmxtrans/agent/Invocation.java
src/main/java/org/jmxtrans/agent/JmxTransConfigurationXmlLoader.java
src/main/java/org/jmxtrans/agent/JmxTransExporter.java
src/main/java/org/jmxtrans/agent/JmxTransExporterConfiguration.java
src/main/java/org/jmxtrans/agent/Query.java
src/main/java/org/jmxtrans/agent/TimeTrackingCollector.java
src/main/java/org/jmxtrans/agent/util/GcdCalculator.java
src/test/java/org/jmxtrans/agent/JmxTransConfigurationXmlLoaderTest.java
src/test/java/org/jmxtrans/agent/QueryTest.java
src/test/java/org/jmxtrans/agent/util/GcdCalculatorTest.java
src/test/resources/jmxtrans-collect-interval-override-test.xml

Support for setting `collectIntervalInSeconds` as an attribute on queries and invocations. Overrides the default setting. For example:
```
<query objectName="java.lang:type=Threading" attributes="ThreadCount,TotalStartedThreadCount"
resultAlias="jvm.threads.#attribute#" collectIntervalInSeconds="5"/>
```
Implementation details:
Collections are still made in a single thread. The thread is scheduled to run at an interval that is equal to the greatest common divisor of the actual collect intervals. On each run, each query/invocation is checked to see if it is time to run that specific query/invocation. The time at which it was last run is remembered to decide when to run next.
See issue #56

Support for overriding the collect interval for individual queries and invocations

---

src/main/java/org/jmxtrans/agent/ExpressionLanguageEngineImpl.java
src/main/java/org/jmxtrans/agent/JmxTransConfigurationXmlLoader.java
src/main/java/org/jmxtrans/agent/JmxTransExporterConfiguration.java
src/main/java/org/jmxtrans/agent/OutputWritersChain.java
src/main/java/org/jmxtrans/agent/PerMinuteSummarizerOutputWriter.java
src/main/java/org/jmxtrans/agent/util/StringUtils2.java
src/main/java/org/jmxtrans/agent/util/collect/EvictingQueue.java
src/test/java/org/jmxtrans/agent/JmxTransConfigurationXmlLoaderTest.java
src/test/java/org/jmxtrans/agent/LibratoMetricsIntegrationTest.java
src/test/java/org/jmxtrans/agent/QueryTest.java
src/test/java/org/jmxtrans/agent/StatsDOutputWriterIntegrationTest.java
src/test/java/org/jmxtrans/agent/util/collect/Iterables2Test.java

This pull request is focused on resolving occurrences of Sonar rule squid:S2293 - “ The diamond operator ("<>") should be used ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2293
Please let me know if you have any questions.
Ayman Abdelghany.

Simplify the generics declaration by using the diamond operator ("<>") to reduce the verbosity of generics code.

---

src/main/java/org/jmxtrans/agent/util/ConfigurationUtils.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1858 - “ "toString()" should never be called on a String object ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1858
Please let me know if you have any questions.
Ayman Abdelghany.

Removing unnecessary toString()

---

README.md

On some OSes, e.g. Ubuntu, getHostName() returns a shortname. Use
getCanonicalHostName to always get an FQDN.
I thought I'd to the legwork and then have the discussion. What do you think about this change? For us it's very annoying to not be able to use `#hostname#` when submitting to Graphite, rather we have to create an ENV variable in the init-script and use that instead.

Document/link to expression language in the README

---

src/main/java/org/jmxtrans/agent/StatsDOutputWriter.java
src/test/java/org/jmxtrans/agent/StatsDOutputWriterIntegrationTest.java
src/test/java/org/jmxtrans/agent/StatsDOutputWriterTest.java

Attempt to fix issue https://github.com/jmxtrans/jmxtrans-agent/issues/44.
I can think of 2 ways of solving this issue:
1. select gauge vs counter based on the metricType, thats the mbean attribute type
2. add a outputWriter config key to globally select gauge vs counter.
I've implemented the 1st.
@NGough34: let me know if this fits your need.

Adding support for StatsD counter/gauges

---

README.md
src/main/java/org/jmxtrans/agent/GraphiteUdpOutputWriter.java
src/main/java/org/jmxtrans/agent/influxdb/InfluxDbOutputWriter.java
src/main/java/org/jmxtrans/agent/influxdb/InfluxMetric.java
src/main/java/org/jmxtrans/agent/influxdb/InfluxMetricConverter.java
src/main/java/org/jmxtrans/agent/influxdb/InfluxTag.java
src/main/java/org/jmxtrans/agent/util/time/Clock.java
src/main/java/org/jmxtrans/agent/util/time/SystemCurrentTimeMillisClock.java
src/test/java/org/jmxtrans/agent/GraphiteUdpOutputWriterTest.java
src/test/java/org/jmxtrans/agent/influxdb/InfluxDbOutputWriterTest.java
src/test/java/org/jmxtrans/agent/influxdb/InfluxMetricConverterTest.java
src/test/java/org/jmxtrans/agent/testutils/FixedTimeClock.java

Output writer for InfluxDb.
A bit experimental since I'm not an Influx expert. However, the changes do not affect anything else so should be safe to merge and let others test it.
Restricted to measurements with one field since I could not come up with a good way to support multiple fields with how we structure queries and writers.
For more information about configuration and how it works see the updated README.md.
@cyrille-leclerc If you have the time, I would appreciate a review.
Fixes #24

Added Experimental InfluxDb output writer

---

src/main/java/org/jmxtrans/agent/FileOverwriterOutputWriter.java
src/main/java/org/jmxtrans/agent/RollingFileOutputWriter.java

Rationale: the current default logging interval is already in seconds.

Add seconds/milliseconds to timestamps

---

pom.xml
src/main/java/org/jmxtrans/agent/influxdb/InfluxDbOutputWriter.java
src/test/java/org/jmxtrans/agent/influxdb/InfluxDbOutputWriterTest.java

This pull request provides the ability to disable the InfluxDbOutputWriter like its Graphite brethren.

Added ability to disable the InfluxDbOutputWriter

---

src/main/java/org/jmxtrans/agent/JmxTransAgent.java
src/main/java/org/jmxtrans/agent/util/logging/Logger.java

#84 configurable output for logger: stdout or stderr. 
Use the environment variable `JMX_TRANS_AGENT_CONSOLE=stderr` or the system property `-Dorg.jmxtrans.agent.util.logging.Logger.console=stderr`

[#84] configurable output for logger: stdout or stderr. 

---

src/main/java/org/jmxtrans/agent/influxdb/InfluxMetric.java
src/test/java/org/jmxtrans/agent/influxdb/InfluxMetricConverterTest.java

Work on #91 
Add test case to check the output for a big float

[#91] InfluxDB - Decimal number formatting (float, double and BigDecimal)

---

src/main/java/org/jmxtrans/agent/StatsDOutputWriter.java
src/test/java/org/jmxtrans/agent/StatsDOutputWriterTest.java

Fix #98 Purge ByteBuffer in case of exceptions sending the message + extend exception catching to RuntimeException

Fix #98 purge ByteBuffer in case of exceptions sending the message

---

src/main/java/org/jmxtrans/agent/influxdb/InfluxMetric.java
src/test/java/org/jmxtrans/agent/influxdb/InfluxMetricTest.java

> All string values must be surrounded in double-quotes ". If the string contains a double-quote or backslashes, it must be escaped with a backslash, e.g. \", \\
https://github.com/influxdata/influxdb/blob/master/tsdb/README.md#fields

String values surrounded in double-quotes. Special characters escaped.

---

src/main/java/org/jmxtrans/agent/graphite/GraphiteMetricMessageBuilder.java
src/test/java/org/jmxtrans/agent/GraphiteMetricMessageBuilderTest.java

Graphite only supports numeric values. It is useful to be able to publish boolean attributes as binary metrics as sometimes we do not own the code that exposes those attributes. 
This is a feature that is already supported by [jmxtrans](https://github.com/jmxtrans/jmxtrans/issues/99).
Apologies for the currently required disclaimer below! :)
This contribution is provided 'as is' and without any warranty or guarantee of any kind, express or implied, including in relation to its quality, suitability for a particular purpose or non-infringement. To the extent permitted by law, in no event shall the creator of this contribution be liable for any claim, damage or other liability, whether arising in contract, tort or otherwise, arising out of or in connection with this contribution.

Convert Boolean attribute into int metrics

---

src/main/java/org/jmxtrans/agent/google/Connection.java
src/main/java/org/jmxtrans/agent/google/MetricWriter.java
src/main/java/org/jmxtrans/agent/google/readme.md

Added an option of sourcing authentication token from Google Container Engine cluster.
OBS! Slight change of behaviour, the Container Engine service account takes precedence over the GOOGLE_APPLICATION_CREDENTIALS. 
Documented the implications.

GoogleWriter: using cluster default account

---

README.md
src/main/java/org/jmxtrans/agent/JmxTransAgent.java

This should be a little more stable and faster than a flat delay.
Let me know what you think and I can try and add a test for it.
Tested with EAP7:
```
2017-12-02 19:30:44.76 INFO [main] org.jmxtrans.agent.JmxTransAgent - jmxtrans agent initialization delayed waiting for MBeanServer
19:30:45,056 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final-redhat-1
2017-12-02 19:30:45.768 INFO [jmxtrans-agent-delayed-starter-waitForMBeanServer] org.jmxtrans.agent.JmxTransAgent - Starting 'JMX metrics exporter agent: 1.2.7-SNAPSHOT' with configuration '/Users/ahenning/Code/jmxtrans-agent/sample-config.xml'...
2017-12-02 19:30:45.77 INFO [jmxtrans-agent-delayed-starter-waitForMBeanServer] org.jmxtrans.agent.JmxTransAgent - PropertiesLoader: Empty Properties Loader
19:30:55,322 INFO …
```

Add option for waiting for an MBeanServer as opposed to flat delay

---

README.md

Added correct tages to indicate xml on the ReadME page.

Fix typo where example not displayed on ReadMe

---

src/main/java/org/jmxtrans/agent/ConsoleOutputWriter.java
src/main/java/org/jmxtrans/agent/Invocation.java
src/main/java/org/jmxtrans/agent/JmxTransConfigurationXmlLoader.java
src/main/java/org/jmxtrans/agent/JmxTransExporterConfiguration.java

Invocations were always getting counted as counters because writeInvocation always ended up as writeQueryResult with null passed as the type. I've short circuited that and wired up the 'type' parameter similar to query.
I'm not married to the change to ConsoleOutputWriter to log what type the metric is.

Add counter type support to invocations

---

README.md
src/main/java/org/jmxtrans/agent/Query.java

Support for a basic type easier and lighter to implement in applications than CompositeData.
Tested on OpenJDK 1.7.0_201

Map support in addition to the current CompositeData

---

.travis.yml
src/main/java/org/jmxtrans/agent/StatsDOutputWriter.java
src/test/java/org/jmxtrans/agent/StatsDOutputWriterTest.java

skip "NaN" or "INF" value in StatsDOutputWriter
this is for resolving issue when integrates jmxtrans-agent with Kafka Connect. the MBean of kafka connect sometimes emits NaN as the value for StatsDOutputWriter as the following.
> can't enable for offset-commit-max-time-ms, err msg as
Invalid value "dynamostreamskafkaconector.task.offset-commit-max-time-ms,connector=firehose-connector,task=1:NaN|g" supplied (NaN or INF)

skip NaN value in StatsDOutputWriter

---

pom.xml

The change from oracle JDK to openJDK broke compilation for `DynamicallyAgentAttacher`

Fix failing CI by adding com.sun.tools.attach dep

---

src/main/java/org/jmxtrans/agent/StatsDOutputWriter.java

This should address the issue when running with a different JRE than the compilation version:
https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

Fixed the JDK version compatibility issue with Buffer class
